### ISSUE TITLE
Mistake when I run the script

### ISSUE THREAD

**Issue by priximmo** [SmeegeSec/HashTag#3]
Helo 

thx for your script. But when I run hashtag.py I hav a syntax error.

It's on this line :
print 'Error parsing LM and NTLM hashes from Domain Cached Credentials/mscash hash'

I'm sorry but I'm beginner on Python.

Can you help me ?

Thx

Xavier

**Comment by SmeegeSec** [comment]
No problem, could you give me the hash you used? you can replace some of
the hexadecimal characters to not reveal the hash if you want, but I would
like to know the format and length of the hash you used.  That would be
really helpful, thanks.

**Comment by priximmo** [comment]
Thnaks for you answer.

But error come when I run script whith Pyhton IDLE. After I run with F5 touch I have this mistake with the message.

I don't have hash to check because I just want to write a post on my blog to introduce your script in my community.

Sorry for my bad english...

Courld you help me ?
![Uploading hash.jpg . . .]()

**Comment by priximmo** [comment]
It's ok. In fact, in Python 3.0 "print" become a function. I must use () for parameter.
